### ISSUE TITLE
Dark Themes: Black text on black background

### ISSUE THREAD

**Issue by BjarkeNL** [FrankConijn/Firefox-Quantum-Rounded-Tabs#1]
This is very cool! :) I didn't think this was possible anymore.

I might be doing something wrong, but when i select a dark theme, after having installed your userChrome.css, the text on the tabs stays black, instead of changing to white as usual. That means that i get black text on (almost) black background. (See screenshot)

Is there a way to fix that?

![image](https://user-images.githubusercontent.com/2156625/50665485-21128280-0fb1-11e9-98fd-9a9905e89d7b.png)

**Comment by FrankConijn** [comment]
Hello BjarkeNL, 

Yes, there is: where it says in the userChrome.css: 'tab text color - customizable'. Just change 'black' to 'white' and reinstall the userChrome.css.
