### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by qeerl** [FrankConijn/Firefox-Quantum-Rounded-Tabs#5]
Hello,
I followed all the instructions and nothing seems to change. I'm using Firefox 68.8.0esr (portable). 
I've double-checked all the operations, and the chrome folder is at the right place.  What can be the issue? 

![FF](https://user-images.githubusercontent.com/30752654/82948669-7b472580-9fa2-11ea-9571-1afc99079608.jpg)

Thanks !

**Comment by FrankConijn** [comment]
Hey qeerl, 

I'm afraid I wouldn't know. I installed it on a new Firefox on a new Win 10, and everything worked perfectly. That was some five months ago, so that could as well have been FF 68. 

Could it have something to do with your version being a portable version? On a USB, I suppose? Could you try installing it the normal way, on your or another machine?

**Comment by qeerl** [comment]
It's the version from Portable Apps and the profile is accessed by symbolic links to an encrypted container mounted as a disk (Steganos Safe). But i've installed a regular version of FF68.9esr to see if I could get if to work, but to no avail.

Anyway, I managed to get what I wanted (with some tweaks to get even more rounded tabs) but I had to use this code in userChrome.css to get it working:

```
/* Firefox Quantum userChrome.css tweaks */
/* Github: https://github.com/aris-t2/customcssforfx */

:root {
  --default_tab_border_roundness: 12px;
}

/* tab top border roundness */
#TabsToolbar .tabbrowser-tab,
#TabsToolbar .tabbrowser-tab .tab-stack,
#TabsToolbar .tabbrowser-tab .tab-background,
#TabsToolbar .tabbrowser-tab .tab-content {
  border-top-left-radius: var(--default_tab_border_roundness) !important;
  border-top-right-radius: var(--default_tab_border_roundness) !important;
  overflow: hidden;
}

#TabsToolbar .tabs-newtab-button{
  border-top-left-radius: var(--default_tab_border_roundness) !important;
  border-top-right-radius: var(--default_tab_border_roundness) !important;
}

#TabsToolbar .tabbrowser-tab {
  border: 1px solid !important;
  border-bottom: none !important;
  border-radius: 10px 10px 0 0 !important;
  # margin: 0px 0px 1px 0px !important;
  # padding: 1px 0 !important;
}

/* hide tab separators AUSGEBLENDET! *
.tabbrowser-tab::after,
.tabbrowser-tab::before {
  opacity: 0 !important;
  border-image: unset !important;
  border-image-slice: unset !important;
  width: unset !important;
}/

#tabbrowser-tabs[movingtab] > .tabbrowser-tab[beforeselected]:not([last-visible-tab])::after,
.tabbrowser-tab:not([selected]):not([afterselected-visible]):not([afterhovered]):not([first-visible-tab]):not(:hover)::before,
#tabbrowser-tabs:not([overflow]) > .tabbrowser-tab[last-visible-tab]:not([selected]):not([beforehovered]):not(:hover)::after {
  content: unset !important;
  display: unset !important;
}
```
http://pc-berater.biz/2019/06/04/firefox-mit-runden-tabs

So everything is fine now, thank you Frank ! 

![Quantum Rounded](https://user-images.githubusercontent.com/30752654/83679326-83751580-a5df-11ea-9d17-bcd35cd8cc25.jpg)
